"""Dados iniciais do Pulso. Espelham o mock que rodava no front.
Persona: Lucas Mendes, 28, analista pleno, R$ 6.800/mês."""

SEED = {
    "user": {
        "name": "Lucas", "fullName": "Lucas Mendes", "initials": "LM", "age": 28,
        "job": "Analista Pleno", "salary": 6800, "bank": "Banco", "paydayDay": 5,
        "todayLabel": "segunda, 9 de junho", "monthLabel": "Junho",
    },
    "balance": {
        "checking": 3700.0, "creditUsed": 1400.0, "creditLimit": 6000.0,
        "creditDueDay": 15, "income": 6800.0, "spent": 2265.0, "estSpend": 7200.0,
        "vsLastMonthPct": -12,
    },
    "health": {
        "score": 58, "scoreLabel": "Atenção", "zone": "atencao", "deltaMonth": -12,
        "headline": "Sua saúde financeira caiu 12 pontos este mês.",
        "subline": "O cartão subiu e o objetivo ficou pra trás. Dá pra reverter.",
        "history": [
            {"m": "Jan", "v": 71}, {"m": "Fev", "v": 68}, {"m": "Mar", "v": 73},
            {"m": "Abr", "v": 70}, {"m": "Mai", "v": 70}, {"m": "Jun", "v": 58},
        ],
        "vitals": [
            {"key": "fluxo", "label": "Fluxo de caixa", "value": 44, "status": "atencao",
             "hint": "Gastando mais rápido que recebe", "detail": "Ritmo de saída vs. entrada no mês"},
            {"key": "cartao", "label": "Uso do cartão", "value": 31, "status": "critico",
             "hint": "Fatura em 45% do limite", "detail": "Quanto do limite está comprometido"},
            {"key": "recorrentes", "label": "Assinaturas", "value": 61, "status": "atencao",
             "hint": "R$ 218/mês em recorrências", "detail": "Peso dos gastos fixos no orçamento"},
            {"key": "reserva", "label": "Reserva", "value": 22, "status": "critico",
             "hint": "0,4 meses de colchão", "detail": "Meses que você aguenta sem renda"},
            {"key": "objetivo", "label": "Objetivos", "value": 38, "status": "atencao",
             "hint": "Intercâmbio 68% · Reserva 17%", "detail": "Progresso médio das metas"},
        ],
    },
    "goals": [
        {"id": "g-intercambio", "name": "Intercâmbio", "icon": "plane", "target": 12000,
         "saved": 8160, "progress": 0.68, "targetDate": "Dez 2026", "monthsLeft": 6,
         "probability": 0.84, "risk": "Médio", "monthlyNeeded": 640, "monthlyCurrent": 480,
         "actions": ["Reduzir gastos com transporte em R$ 80", "Aplicar saldo parado automaticamente"]},
        {"id": "g-reserva", "name": "Reserva de emergência", "icon": "shield", "target": 5400,
         "saved": 900, "progress": 0.17, "targetDate": "Mar 2027", "monthsLeft": 9,
         "probability": 0.61, "risk": "Alto", "monthlyNeeded": 500, "monthlyCurrent": 150,
         "actions": ["Separar R$ 150 automático no dia 5 (salário)", "Direcionar 50% do 13º pra reserva"]},
        {"id": "g-cartao", "name": "Quitar o cartão", "icon": "card", "target": 1870,
         "saved": 0, "progress": 0.0, "targetDate": "Fev 2027", "monthsLeft": 8,
         "probability": 0.73, "risk": "Médio", "monthlyNeeded": 240, "monthlyCurrent": 90,
         "actions": ["Cortar 2 deliveries/semana libera ~R$ 240/mês", "Pausar 1 assinatura não usada (−R$ 34)"]},
    ],
    "transactions": [
        {"id": "t1", "merchant": "iFood", "category": "Delivery", "icon": "food", "amount": -47.9, "when": "Hoje, 12:40"},
        {"id": "t2", "merchant": "Netflix", "category": "Assinatura", "icon": "film", "amount": -44.9, "when": "Hoje, 03:00"},
        {"id": "t3", "merchant": "Uber", "category": "Transporte", "icon": "car", "amount": -18.7, "when": "Ontem, 22:15"},
        {"id": "t4", "merchant": "iFood", "category": "Delivery", "icon": "food", "amount": -62.3, "when": "Ontem, 20:50", "flagged": True},
        {"id": "t5", "merchant": "Academia SmartFit", "category": "Saúde", "icon": "gym", "amount": -109.9, "when": "7 jun"},
        {"id": "t6", "merchant": "Pix recebido", "category": "Entrada", "icon": "arrow-in", "amount": 150.0, "when": "6 jun"},
        {"id": "t7", "merchant": "Salário", "category": "Entrada", "icon": "briefcase", "amount": 3400.0, "when": "5 jun"},
        {"id": "t8", "merchant": "Seguro Vida+", "category": "Recorrente", "icon": "shield", "amount": -63.2, "when": "5 jun", "flagged": True},
    ],
    "levers": [
        {"id": "delivery", "label": "Delivery", "icon": "food", "current": 340, "max": 240},
        {"id": "transporte", "label": "Transporte por app", "icon": "car", "current": 180, "max": 120},
        {"id": "assinaturas", "label": "Assinaturas", "icon": "film", "current": 218, "max": 90},
        {"id": "lazer", "label": "Bares e lazer", "icon": "film", "current": 260, "max": 180},
        {"id": "compras", "label": "Compras online", "icon": "card", "current": 190, "max": 150},
        {"id": "academia", "label": "Academia", "icon": "gym", "current": 110, "max": 110},
    ],
    "projection": {
        "expected": -180, "optimistic": 320, "pessimistic": -640, "probabilityNegative": 0.72,
        "todayIndex": 9, "daysInMonth": 30,
        "driver": "O que mais pesa: cartão + delivery na 1ª quinzena.",
        "median": [1690, 1610, 1540, 1505, 1430, 3360, 3180, 2960, 1284, 1150, 1010, 880, 720,
                   560, -120, -180, -260, -300, -340, -360, -390, -410, -440, -460, -480, -500,
                   -520, -540, -560, -180],
        "upper": [1740, 1700, 1660, 1640, 1600, 3520, 3400, 3220, 1620, 1540, 1470, 1390,
                  1300, 1220, 980, 940, 900, 880, 860, 850, 840, 840, 850, 860, 880, 900, 930,
                  960, 1000, 320],
        "lower": [1640, 1520, 1420, 1370, 1260, 3200, 2960, 2700, 940, 760, 560, 360, 140,
                  -80, -1020, -1100, -1180, -1240, -1300, -1350, -1400, -1450, -1500, -1550,
                  -1600, -1650, -1700, -1750, -1800, -640],
    },
    "recommendations": [
        {"id": "r-delivery", "icon": "food", "title": "Delivery está comendo seu mês",
         "text": "Você gasta 22% da renda com delivery. Reduzir para 15% libera R$ 180 por mês.",
         "impact": "+R$ 180 / mês", "cta": "Aplicar no plano", "tone": "amber"},
        {"id": "r-salario", "icon": "trend", "title": "Aproveite os próximos aumentos",
         "text": "Seu salário sobe ~8% ao ano. Investindo metade dos futuros aumentos, sua meta é antecipada em 14 meses.",
         "impact": "−14 meses", "cta": "Simular", "tone": "mint"},
        {"id": "r-transporte", "icon": "car", "title": "Transporte mexe na sua meta",
         "text": "Cortar R$ 80/mês em transporte eleva a probabilidade do Intercâmbio de 84% para 91%.",
         "impact": "+7% na meta", "cta": "Aplicar", "tone": "blue"},
    ],
    "insight": {
        "badge": "Insight de hoje", "icon": "food",
        "title": "Você gastou R$ 340 com delivery este mês.",
        "body": "É 3x mais que em abril e já passou do que você gasta com mercado. Quer revisar?",
        "primary": "Revisar gastos", "secondary": "Agora não",
    },
}

# ---------------------------------------------------------------------------
# Persona demo: Joao Pedro, 21 anos, estagiario de TI, R$ 4.000/mes
# Gastos tipicos: delivery pesado, academia, baladas, streaming, Uber
# ---------------------------------------------------------------------------
DEMO_SEED = {
    "user": {
        "name": "Joao Pedro", "fullName": "Joao Pedro Alves", "initials": "JP", "age": 21,
        "job": "Estagiario de TI", "salary": 4000, "bank": "Nubank", "paydayDay": 5,
        "todayLabel": "quinta, 11 de junho", "monthLabel": "Junho",
    },
    "balance": {
        "checking": 1240.0, "creditUsed": 760.0, "creditLimit": 3000.0,
        "creditDueDay": 12, "income": 4000.0, "spent": 1870.0, "estSpend": 4320.0,
        "vsLastMonthPct": 8,
    },
    "health": {
        "score": 47, "scoreLabel": "Critico", "zone": "critico", "deltaMonth": -8,
        "headline": "Voce esta gastando mais do que ganha este mes.",
        "subline": "Delivery e baladas consumiram 47% da renda em 10 dias. Ainda da pra frear.",
        "history": [
            {"m": "Jan", "v": 55}, {"m": "Fev", "v": 52}, {"m": "Mar", "v": 60},
            {"m": "Abr", "v": 58}, {"m": "Mai", "v": 55}, {"m": "Jun", "v": 47},
        ],
        "vitals": [
            {"key": "fluxo", "label": "Fluxo de caixa", "value": 32, "status": "critico",
             "hint": "Ritmo de gasto vai estourar a renda", "detail": "Ritmo de saida vs. entrada no mes"},
            {"key": "cartao", "label": "Uso do cartao", "value": 25, "status": "atencao",
             "hint": "Fatura em 25% do limite", "detail": "Quanto do limite esta comprometido"},
            {"key": "recorrentes", "label": "Assinaturas", "value": 58, "status": "atencao",
             "hint": "R$ 167/mes em recorrencias", "detail": "Peso dos gastos fixos no orcamento"},
            {"key": "reserva", "label": "Reserva", "value": 15, "status": "critico",
             "hint": "0,3 meses de colchao", "detail": "Meses que voce aguenta sem renda"},
            {"key": "objetivo", "label": "Objetivos", "value": 22, "status": "critico",
             "hint": "Viagem 20% . Reserva 5%", "detail": "Progresso medio das metas"},
        ],
    },
    "goals": [
        {"id": "g-viagem", "name": "Viagem com a galera", "icon": "plane", "target": 3500,
         "saved": 700, "progress": 0.20, "targetDate": "Dez 2026", "monthsLeft": 6,
         "probability": 0.51, "risk": "Alto", "monthlyNeeded": 467, "monthlyCurrent": 120,
         "actions": ["Cortar 4 deliveries/mes libera ~R$ 200", "Pausar uma assinatura (menos R$ 45)"]},
        {"id": "g-reserva", "name": "Reserva de emergencia", "icon": "shield", "target": 12000,
         "saved": 600, "progress": 0.05, "targetDate": "Jun 2028", "monthsLeft": 24,
         "probability": 0.40, "risk": "Alto", "monthlyNeeded": 475, "monthlyCurrent": 60,
         "actions": ["Separar R$ 100 automatico no dia 5", "Cada real poupado no delivery vai pra reserva"]},
    ],
    "transactions": [
        {"id": "d-t1",  "merchant": "iFood",           "category": "Delivery",   "icon": "food",      "amount": -52.90, "when": "Hoje, 13:20"},
        {"id": "d-t2",  "merchant": "Rappi",            "category": "Delivery",   "icon": "food",      "amount": -38.50, "when": "Hoje, 20:10"},
        {"id": "d-t3",  "merchant": "Uber",             "category": "Transporte", "icon": "car",       "amount": -22.30, "when": "Ontem, 23:45"},
        {"id": "d-t4",  "merchant": "99",               "category": "Transporte", "icon": "car",       "amount": -18.90, "when": "Ontem, 03:10", "flagged": True},
        {"id": "d-t5",  "merchant": "Bar Republica",    "category": "Lazer",      "icon": "film",      "amount": -112.0, "when": "Ontem, 01:30", "flagged": True},
        {"id": "d-t6",  "merchant": "iFood",            "category": "Delivery",   "icon": "food",      "amount": -45.20, "when": "8 jun"},
        {"id": "d-t7",  "merchant": "SmartFit",         "category": "Saude",      "icon": "gym",       "amount": -109.90,"when": "7 jun"},
        {"id": "d-t8",  "merchant": "Spotify",          "category": "Assinatura", "icon": "film",      "amount": -11.90, "when": "5 jun"},
        {"id": "d-t9",  "merchant": "Netflix",          "category": "Assinatura", "icon": "film",      "amount": -44.90, "when": "5 jun"},
        {"id": "d-t10", "merchant": "Salario",          "category": "Entrada",    "icon": "briefcase", "amount": 4000.0, "when": "5 jun"},
        {"id": "d-t11", "merchant": "iFood",            "category": "Delivery",   "icon": "food",      "amount": -67.80, "when": "4 jun", "flagged": True},
        {"id": "d-t12", "merchant": "Shopee",           "category": "Compras",    "icon": "card",      "amount": -139.90,"when": "3 jun"},
        {"id": "d-t13", "merchant": "Uber",             "category": "Transporte", "icon": "car",       "amount": -34.50, "when": "2 jun"},
        {"id": "d-t14", "merchant": "Bar da Fac",       "category": "Lazer",      "icon": "film",      "amount": -87.00, "when": "1 jun"},
        {"id": "d-t15", "merchant": "iFood",            "category": "Delivery",   "icon": "food",      "amount": -41.30, "when": "1 jun"},
        {"id": "d-t16", "merchant": "Pix recebido",     "category": "Entrada",    "icon": "arrow-in",  "amount": 200.0,  "when": "31 mai"},
        {"id": "d-t17", "merchant": "HBO Max",          "category": "Assinatura", "icon": "film",      "amount": -34.90, "when": "30 mai"},
        {"id": "d-t18", "merchant": "iFood",            "category": "Delivery",   "icon": "food",      "amount": -58.40, "when": "29 mai"},
        {"id": "d-t19", "merchant": "99",               "category": "Transporte", "icon": "car",       "amount": -27.60, "when": "28 mai"},
        {"id": "d-t20", "merchant": "Show Lolla",       "category": "Lazer",      "icon": "film",      "amount": -320.0, "when": "27 mai", "flagged": True},
    ],
    "levers": [
        {"id": "delivery",    "label": "Delivery",          "icon": "food", "current": 450, "max": 200},
        {"id": "lazer",       "label": "Bares e baladas",   "icon": "film", "current": 380, "max": 200},
        {"id": "transporte",  "label": "Transporte por app","icon": "car",  "current": 220, "max": 120},
        {"id": "assinaturas", "label": "Assinaturas",       "icon": "film", "current": 167, "max": 80},
        {"id": "compras",     "label": "Compras online",    "icon": "card", "current": 210, "max": 120},
        {"id": "academia",    "label": "Academia",          "icon": "gym",  "current": 110, "max": 110},
    ],
    "projection": {
        "expected": -320, "optimistic": 180, "pessimistic": -820, "probabilityNegative": 0.81,
        "todayIndex": 11, "daysInMonth": 30,
        "driver": "O que mais pesa: delivery + baladas toda semana.",
        "median": [1870,1760,1640,1560,1460,5420,5180,4960,4740,4520,4300,
                   4050,3820,3590,3360,3140,2900,2660,2420,2180,1940,1700,
                   1440,1180,920,660,400,80,-200,-320],
        "upper":  [1920,1840,1760,1700,1640,5580,5400,5220,5040,4880,4720,
                   4540,4360,4200,4040,3880,3720,3560,3400,3240,3080,2920,
                   2740,2560,2380,2200,2020,1780,1540,180],
        "lower":  [1820,1680,1520,1420,1280,5260,4960,4700,4440,4160,3880,
                   3560,3280,2980,2680,2400,2080,1760,1440,1120,800,480,140,
                   -200,-540,-880,-1220,-1560,-1940,-820],
    },
    "recommendations": [
        {"id": "rd-delivery", "icon": "food", "title": "Delivery e o maior gasto do mes",
         "text": "R$ 450 em delivery supera academia, transporte e streaming somados. Cortar pela metade libera R$ 225.",
         "impact": "+R$ 225 / mes", "cta": "Ver no plano", "tone": "amber"},
        {"id": "rd-lazer", "icon": "film", "title": "Baladas pesando no bolso",
         "text": "Voce gastou R$ 199 em bares e festas so esta semana. Um teto de R$ 200/mes muda tudo.",
         "impact": "-R$ 180 / mes", "cta": "Criar teto", "tone": "amber"},
        {"id": "rd-reserva", "icon": "shield", "title": "Sem reserva voce ta no limite",
         "text": "Com 0,3 meses de colchao, qualquer imprevisto vai pro cartao. R$ 100/mes ja muda a trajetoria.",
         "impact": "Score +12 pts", "cta": "Automatizar", "tone": "blue"},
    ],
    "insight": {
        "badge": "Insight de hoje", "icon": "food",
        "title": "Voce pediu delivery 5 vezes esta semana.",
        "body": "Em 10 dias de junho ja foram R$ 246 no iFood e Rappi. No ritmo atual passa de R$ 450 no mes.",
        "primary": "Ver gastos", "secondary": "Agora nao",
    },
}
